<a href="https://colab.research.google.com/github/Abel-Kurian/Ai-internship/blob/main/Day4_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')


df = pd.read_csv("/content/nlp_dataset.csv")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [2]:
df

                                                Text
0  Natural Language Processing is a fascinating f...
1  It bridges the gap between humans and machines...
2  NLP techniques are widely used in applications...
3  Machine translation and speech recognition are...
4  Despite its advancements, NLP faces challenges...
5  Continuous research and innovation are improvi...
6  The potential of NLP is vast, making it essent...

In [5]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [11]:
def process_text(text):
    word_tokens = word_tokenize(text)

    #stopword removal
    filtered_tokens = [word for word in word_tokens if word.lower() not in stop_words]

    lemmatized_tokens = [lemmatizer.lemmatize(word) for word in filtered_tokens]

    return {
        "original text":text,
        "word tokens":word_tokens,
        "filtered tokens":filtered_tokens,
        "lemmatized tokens":lemmatized_tokens
      }
results = df["Text"].apply(process_text)

processed_df = pd.DataFrame(results.tolist())

print(processed_df.head)

processed_file_path = "processed_file_datase.csv"
processed_df.to_csv(processed_file_path, index=False)
print("procc=essed dataset saved to",processed_file_path)

<bound method NDFrame.head of                                        original text  ...                                  lemmatized tokens
0  Natural Language Processing is a fascinating f...  ...  [Natural, Language, Processing, fascinating, f...
1  It bridges the gap between humans and machines...  ...  [bridge, gap, human, machine, enabling, comput...
2  NLP techniques are widely used in applications...  ...  [NLP, technique, widely, used, application, ch...
3  Machine translation and speech recognition are...  ...  [Machine, translation, speech, recognition, co...
4  Despite its advancements, NLP faces challenges...  ...  [Despite, advancement, ,, NLP, face, challenge...
5  Continuous research and innovation are improvi...  ...  [Continuous, research, innovation, improving, ...
6  The potential of NLP is vast, making it essent...  ...  [potential, NLP, vast, ,, making, essential, m...

[7 rows x 4 columns]>
procc=essed dataset saved to processed_file_datase.csv

In [10]:
results

0    {'original text': 'Natural Language Processing...
1    {'original text': 'It bridges the gap between ...
2    {'original text': 'NLP techniques are widely u...
3    {'original text': 'Machine translation and spe...
4    {'original text': 'Despite its advancements, N...
5    {'original text': 'Continuous research and inn...
6    {'original text': 'The potential of NLP is vas...
Name: Text, dtype: object